- name: Configure and install kubernetes
  hosts: kubernetes_master,kubernetes_slave
  tasks:
    - name: yum
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - conntrack
        - ntpdate
        - ntp
        - ipvsadm
        - ipset
        - jq
        - iptables
        - curl
        - sysstat
        - libseccomp
        - wget
        - vim
        - net-tools
    - name: test
      shell: getenforce
      register: selinux
    - debug: var=selinux
    - name: setenforce
      shell: setenforce 0
      when: selinux.stdout != "Disabled"
    - name: Change SELINUX
      lineinfile: 
        dest: /etc/selinux/config
        regexp: '^SELINUX='
        line: '^SELINUX=disable'
    - name: close swap
      shell: swapoff -a
    - name: config /etc/fstab
      shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
    - name: Close firewalld
      shell: systemctl stop firewalld && systemctl disable firewalld
    - name: config /etc/sysctl.d/kubernetes.conf
      template: src=templates/kubernetes.conf.j2 dest=/etc/sysctl.d/kubernetes.conf
    - name: sysctl -p kubernetes.conf
      shell: sysctl -p /etc/sysctl.d/kubernetes.conf
    - name: create log dir
      file: 
        path: /var/log/journal
        state: directory
    - name: create journald.conf.d
      file: 
        path: /etc/systemd/journald.conf.d
        state: directory
    - name: config log conf
      template: src=templates/99-prophet.conf.j2 dest=/etc/systemd/journald.conf.d/99-prophet.conf
    - name: restart systemd-journald
      service: name=systemd-journald state=restarted
    - name: load br_netfilter module
      shell: modprobe br_netfilter
    - name: config ipvs.modules
      template: src=templates/ipvs.modules.j2 dest=/etc/sysconfig/modules/ipvs.modules
    - name: chmod ipvs.modules
      shell: chmod 755 /etc/sysconfig/modules/ipvs.modules
    - name: bash ipvs.modules
      command: bash /etc/sysconfig/modules/ipvs.modules
    - name: cp kubernetes.tar.gz
      unarchive: src=files/kubernetes.tar.gz dest=/opt/
    - name: rpm install k8s
      shell: chdir=/opt/kubernetes/k8s-1.15.1-rpm rpm -ivh *
    - name: load images
      shell: chdir=/opt/kubernetes/kubeadm-basic.images docker load --input apiserver.tar
    - shell: chdir=/opt/kubernetes/kubeadm-basic.images docker load --input coredns.tar
    - shell: chdir=/opt/kubernetes/kubeadm-basic.images docker load --input etcd.tar
    - shell: chdir=/opt/kubernetes/kubeadm-basic.images docker load --input kubec-con-man.tar
    - shell: chdir=/opt/kubernetes/kubeadm-basic.images docker load --input pause.tar
    - shell: chdir=/opt/kubernetes/kubeadm-basic.images docker load --input proxy.tar
    - shell: chdir=/opt/kubernetes/kubeadm-basic.images docker load --input scheduler.tar
- name: Init kubernetes
  hosts: kubernetes_master
  tasks:
    - name: init cluster
      shell: kubeadm init --apiserver-advertise-address={{ansible_default_ipv4['address']}} --kubernetes-version v1.15.1 --service-cidr=10.96.0.0/12 --pod-network-cidr=10.244.0.0/16
    - name: create .kube
      file:
        path: /root/.kube
        state: directory
    - name: cp admin.conf
      shell: cp -i /etc/kubernetes/admin.conf /root/.kube/config
    - name: chown config
      shell: chown root:root /root/.kube/config
    - name: install flannel
      shell: chdir=/opt/kubernetes/flannel kubectl create -f flannel.yaml
    - name: create token
      shell: kubeadm token create
      register: token
    - set_fact: token={{token.stdout}}
    - name: create sha
      shell: openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
      register: sha
    - set_fact: sha={{sha.stdout}}
    - name: fetch admin.conf to source hosts
      fetch: src=/etc/kubernetes/admin.conf dest=templates/admin.conf flat=yes
- name: Join kubernetes cluster
  hosts: kubernetes_slave
  tasks:
    - name: copy admin.conf
      template: src=templates/admin.conf dest=/etc/kubernetes/admin.conf
    - name: create .kube
      file:
        path: /root/.kube
        state: directory
    - name: cp admin.conf to $HOME
      template: src=templates/admin.conf dest=/root/.kube/config
    - name: chown config
      shell: chown root:root /root/.kube/config
    - name: join cluster
      shell: kubeadm join {{groups['kubernetes_master']|first}}:6443 --token {{ hostvars[groups['kubernetes_master'][0]]['token'] }} --discovery-token-ca-cert-hash sha256:{{ hostvars[groups['kubernetes_master'][0]]['sha'] }}
    