- name: Configure webserver with nginx
  hosts: all
  tasks:
    - name: delete system jdk noarch
      shell: rpm -qa | grep java |grep -v  ".noarch" |xargs -l -t rpm -e --nodeps
    - name:  copy jdk-8u271-linux-x64.tar.gz remote hosts
      unarchive: src=files/jdk-8u271-linux-x64.tar.gz dest=/opt/clouddata/modules/
    - name: java_profile config
      shell: /bin/echo {{ item }} >> /etc/profile && source /etc/profile
      with_items:
        - export JAVA_HOME=/opt/clouddata/modules/jdk1.8.0_271
        - export JRE_HOME=/opt/clouddata/modules/jdk1.8.0_271/jre
        - export CLASSPATH=.:\$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:\$JRE_HOME/lib:\$CLASSPATH
        - export PATH=\$JAVA_HOME/bin:\$PATH
    - name: NTP sync
      shell: ntpdate cn.pool.ntp.org
    - name: Close firewalld
      shell: systemctl stop firewalld && systemctl disable firewalld
    - name: once Change selinux
      shell: setenforce 0
    - name: Change SELINUX
      lineinfile: 
        dest: /etc/selinux/config
        regexp: '^SELINUX='
        line: '^SELINUX=disable'

      

# 如果已经删除了系统自带的jdk可能会报错