- name: Configure webserver with nacos
  hosts: nacos
  vars:
    nacos_dir: "nacos"
  tasks:
    - name: copy nacos
      unarchive: src=nacos-server-1.1.4.tar.gz dest=/opt/clouddata/modules
    - name:  config nacos service
      template: src=nacos.service.j2 dest=/etc/systemd/system/nacos.service
    - name: boot nacos service
      service: name=nacos state=started